M48
; DRILL file KiCad 10.0.3 date 2026-06-23T00:25:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-23T00:25:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
%
G90
G05
T1
X33.395Y-51.0
X33.395Y-54.0
T2
X43.15Y-40.95
X75.4Y-40.95
X75.425Y-83.05
M30
